spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8080

weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "/OpTr2jhf6H+Sm4QWw/dIuj/JqoytGvD4zqTJ0sqL5rtqnBFVdG55phsDeMqxaWHyVmetB8pr5FPhP17zQ7Y0Q=="


